### ISSUE TITLE
Error connecting to Tableau Server - "Redaction only works on xml saved as str or bytes" 

### ISSUE THREAD

**Issue by C412C** [tableau/server-client-python#1199]
**Describe the bug**

Hi, all. Trying to make the switch from Tableau_API_Lib where I can connect and read data with no issues. I can create my server object fine and can manually make changes if I try (tried default first, then tried changing things for troubleshooting) but they don't seem to actually work. For example, if I do print(server.version) on default settings, it says 2.3 so I tried setting it manually to 3.14 (as the docs say I should be using and which works on API Lib) but it didn't seem to do anything. Before it errors, server.use_server_version() seems to change it to 2.4 then breaks as in the code below. Any ideas?

**Versions**
Details of your environment, including:
 - Tableau Server version: 2021.4.1
 - Python version: 3.10
 - TSC library version: 0.24

**To Reproduce**

import tableauserverclient as TSC
tableau_auth = TSC.PersonalAccessTokenAuth(personal_access_token_name, personal_access_token_secret)
server = TSC.Server('http://...')
server.add_http_options({'verify': False})
server.use_server_version()

Traceback (most recent call last):

  File "<ipython-input-134-e10b650803f0>", line 1, in <module>
    server.use_server_version()

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\tableauserverclient\server\server.py", line 176, in use_server_version
    self.version = self._determine_highest_version()

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\tableauserverclient\server\server.py", line 169, in _determine_highest_version
    version = self._get_legacy_version()

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\tableauserverclient\server\server.py", line 148, in _get_legacy_version
    response = dest._make_request(method=self.session.get, url=self.server_address + "/auth?format=xml")

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 89, in _make_request
    loggable_response = self.log_response_safely(server_response)

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 124, in log_response_safely
    loggable_response = helpers.strings.redact_xml(server_response.content.decode(server_response.encoding))

  File "C:\Program Files\Anaconda3\lib\functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)

  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\tableauserverclient\helpers\strings.py", line 34, in redact_xml
    raise TypeError("Redaction only works on xml saved as str or bytes")

TypeError: Redaction only works on xml saved as str or bytes

If I try to do use_server_version=True method in the server setup, I fail on locally signed ssl certificates. That's why the http options but will get certificates once I resolve issues.

I tried to do server.datasources.get() to verify it wasn't working and also got the "Redaction only works on xml saved as str or bytes" error, as well

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by jacalata** [comment]
You can put the http options in the call to create the server, which means it will handle the https correctly from the start. 

server = TSC.Server(url, http_options={})

That said, it shouldn't fail this way anyhow so I'll take a look.

**Comment by C412C** [comment]
Looks like my work had me locked down uber strict and I was using very old packages. Not sure exactly which package was the culprit in this but it looks like something resolved the issue. Apologies for the hassle.
