### ISSUE TITLE
Workbooks publish Bad Request

### ISSUE THREAD

**Issue by v3111707** [tableau/server-client-python#238]
Hello 

There was a problem publishing the workbook. 

The next code returns error.

` import tableauserverclient as TSC

username = 'user'
password = 'password'
server_url = 'https://hostname'
content_url = 'site_url'

tableau_auth = TSC.TableauAuth(username, password, site_id=content_url)
server = TSC.Server(server_url)
server.auth.sign_in(tableau_auth)
all_workbook_items, pagination_item = server.workbooks.get()
wb_id = 'f7ac1ee0-3cb7-4b20-b8d1-a494d56ba561'
file_path = server.workbooks.download(wb_id)

project_id = '79a41078-cd9e-4b83-9bb9-001c01a5faf6'
wb_item = TSC.WorkbookItem(name='test report', project_id=project_id)
wb_item = server.workbooks.publish(wb_item, file_path, 'Overwrite') `

Error:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Sergey/PycharmProjects/Tableau_transfer/test_bug.py", line 18, in <module>
    wb_item = server.workbooks.publish(wb_item, file_path, 'Overwrite')
  File "C:\Users\Sergey\PycharmProjects\envs\Tableau_transfer\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 108, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Sergey\PycharmProjects\envs\Tableau_transfer\lib\site-packages\tableauserverclient\server\endpoint\workbooks_endpoint.py", line 197, in publish
    server_response = self.post_request(url, xml_request, content_type)
  File "C:\Users\Sergey\PycharmProjects\envs\Tableau_transfer\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 78, in post_request
    content_type=content_type)
  File "C:\Users\Sergey\PycharmProjects\envs\Tableau_transfer\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 43, in _make_request
    self._check_status(server_response)
  File "C:\Users\Sergey\PycharmProjects\envs\Tableau_transfer\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 55, in _check_status
    raise ServerResponseError.from_response(server_response.content, self.parent_srv.namespace)
tableauserverclient.server.endpoint.exceptions.ServerResponseError: 

	400011: Bad Request
		There was a problem publishing the file 'test report.twb'.

Process finished with exit code 1

**Comment by gaoang2148** [comment]
This error might because missing credentials for underlying datasource in the workbook. If that's the case, please check [here](https://tableau.github.io/server-client-python/docs/api-ref#connectioncredentials-class) and try add it as optional param for workbook publishing.

**Comment by irwando** [comment]
Old issue with no update.  If you are experiencing issues still please open a new item with details.

**Comment by krishnasaiv** [comment]
Thanks, @gaoang2148 ,
Once I fixed the missing credentials in each data source, the code was working again.
