### ISSUE TITLE
Invalid value: SiteAdministratorExplorer. site_role must be of type Roles

### ISSUE THREAD

**Issue by breakaway83** [tableau/server-client-python#289]
According to https://onlinehelp.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm, seems there are new roles defined, e.g. **SiteAdministratorExplorer** and **SiteAdministratorCreator**, but this library does not keep up-to-date:
`2018-04-24 17:29:43,180 - OffboardingTool - ERROR - [2018-04-24 17:29:43 +0000] [279] [ERROR] Error handling request /tableau/allusers
2018-04-24 17:29:43,180 - OffboardingTool - ERROR - Traceback (most recent call last):
2018-04-24 17:29:43,180 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
2018-04-24 17:29:43,180 - OffboardingTool - ERROR -     self.handle_request(listener, req, client, addr)
2018-04-24 17:29:43,180 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
2018-04-24 17:29:43,181 - OffboardingTool - ERROR -     respiter = self.wsgi(environ, resp.start_response)
2018-04-24 17:29:43,181 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
2018-04-24 17:29:43,181 - OffboardingTool - ERROR -     return self.wsgi_app(environ, start_response)
2018-04-24 17:29:43,181 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
2018-04-24 17:29:43,181 - OffboardingTool - ERROR -     response = self.handle_exception(e)
2018-04-24 17:29:43,181 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
2018-04-24 17:29:43,181 - OffboardingTool - ERROR -     reraise(exc_type, exc_value, tb)
2018-04-24 17:29:43,181 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
2018-04-24 17:29:43,181 - OffboardingTool - ERROR -     response = self.full_dispatch_request()
2018-04-24 17:29:43,181 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
2018-04-24 17:29:43,182 - OffboardingTool - ERROR -     rv = self.handle_user_exception(e)
2018-04-24 17:29:43,182 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
2018-04-24 17:29:43,182 - OffboardingTool - ERROR -     reraise(exc_type, exc_value, tb)
2018-04-24 17:29:43,182 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
2018-04-24 17:29:43,182 - OffboardingTool - ERROR -     rv = self.dispatch_request()
2018-04-24 17:29:43,182 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
2018-04-24 17:29:43,182 - OffboardingTool - ERROR -     return self.view_functions[rule.endpoint](**req.view_args)
2018-04-24 17:29:43,182 - OffboardingTool - ERROR -   File "server/__init__.py", line 91, in wrapper
2018-04-24 17:29:43,182 - OffboardingTool - ERROR -     return f(*args, **kwargs)
2018-04-24 17:29:43,182 - OffboardingTool - ERROR -   File "server/__init__.py", line 425, in tableau_dynamic_allusers
2018-04-24 17:29:43,183 - OffboardingTool - ERROR -     res = app.config['tableau'].get_allusers()
2018-04-24 17:29:43,183 - OffboardingTool - ERROR -   File "services/tableau.py", line 33, in wrapper
2018-04-24 17:29:43,183 - OffboardingTool - ERROR -     return f(*args)
2018-04-24 17:29:43,183 - OffboardingTool - ERROR -   File "services/tableau.py", line 57, in get_allusers
2018-04-24 17:29:43,183 - OffboardingTool - ERROR -     (users, pagination) = self.server.users.get()
2018-04-24 17:29:43,183 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 108, in wrapper
2018-04-24 17:29:43,183 - OffboardingTool - ERROR -     return func(self, *args, **kwargs)
2018-04-24 17:29:43,183 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/tableauserverclient/server/endpoint/users_endpoint.py", line 23, in get
2018-04-24 17:29:43,183 - OffboardingTool - ERROR -     all_user_items = UserItem.from_response(server_response.content, self.parent_srv.namespace)
2018-04-24 17:29:43,183 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/tableauserverclient/models/user_item.py", line 127, in from_response
2018-04-24 17:29:43,184 - OffboardingTool - ERROR -     user_item = cls(name, site_role)
2018-04-24 17:29:43,184 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/tableauserverclient/models/user_item.py", line 33, in __init__
2018-04-24 17:29:43,184 - OffboardingTool - ERROR -     self.site_role = site_role
2018-04-24 17:29:43,184 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/tableauserverclient/models/property_decorators.py", line 43, in wrapper
2018-04-24 17:29:43,184 - OffboardingTool - ERROR -     return func(self, value)
2018-04-24 17:29:43,184 - OffboardingTool - ERROR -   File "/usr/lib/python2.7/site-packages/tableauserverclient/models/property_decorators.py", line 18, in wrapper
2018-04-24 17:29:43,184 - OffboardingTool - ERROR -     raise ValueError(error)
2018-04-24 17:29:43,184 - OffboardingTool - ERROR - ValueError: Invalid value: SiteAdministratorExplorer. site_role must be of type Roles.`

**Comment by reevery** [comment]
@breakaway83 are you running 2018.1, and have you updated to use v0.6.3 which implements the new roles?

**Comment by t8y8** [comment]
I believe this was addressed in recent versions and against the `development` branch. Can you confirm what version you're using?

**Comment by irwando** [comment]
Closing old issues with no response.  Please reopen if this is still an issue.  Make sure you are using the correct versions or newer as specified above.
