### ISSUE TITLE
Can't run sample login code to login to server.

### ISSUE THREAD

**Issue by HarveySummers** [tableau/server-client-python#302]
I can log into my tableau server 10.5 but when I run this sample code with the same account.  I get an XML error.

Running Anaconda Python 3.6 on a Win7 64b laptop.

```
import tableauserverclient as TSC
tableau_auth = TSC.TableauAuth('DumbUser', 'Pa55W0rd')
server = TSC.Server(r'http://tableauserver.corp.com/')

with server.auth.sign_in(tableau_auth):
    all_datasources, pagination_item = server.datasources.get()
    print("\nThere are {} datasources on site: ".format(pagination_item.total_available))
    print([datasource.name for datasource in all_datasources])

# executed in 220ms, finished 12:39:23 2018-06-15
```
Traceback (most recent call last):

 ```
 File "C:\Users\me\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-5-6e7809d1b071>", line 6, in <module>
    with server.auth.sign_in(tableau_auth):

  File "C:\Users\me\AppData\Local\Continuum\Anaconda3\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 108, in wrapper
    return func(self, *args, **kwargs)

  File "C:\Users\me\AppData\Local\Continuum\Anaconda3\lib\site-packages\tableauserverclient\server\endpoint\auth_endpoint.py", line 32, in sign_in
    self._check_status(server_response)

  File "C:\Users\me\AppData\Local\Continuum\Anaconda3\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 55, in _check_status
    raise ServerResponseError.from_response(server_response.content, self.parent_srv.namespace)

  File "C:\Users\me\AppData\Local\Continuum\Anaconda3\lib\site-packages\tableauserverclient\server\endpoint\exceptions.py", line 17, in from_response
    parsed_response = ET.fromstring(resp)

  File "C:\Users\me\AppData\Local\Continuum\Anaconda3\lib\xml\etree\ElementTree.py", line 1314, in XML
    parser.feed(text)

  File "<string>", line unknown
ParseError: mismatched tag: line 3, column 148
```

**Comment by RussTheAerialist** [comment]
Can you run a fiddler (or wireshark) trace to give us what the response coming back from the server is?

**Comment by HarveySummers** [comment]
Fiddler shows nothing – its not even getting to that point.

**Comment by sks786** [comment]
I am also facing same issue.
Below is the code that I am using:

import tableauserverclient as TSC 
tableau_auth = TSC.TableauAuth('username', 'password')
server = TSC.Server('https://server_name.com/')
server.auth.sign_in(tableau_auth)

Below is the error message:

[‎8/‎23/‎2018 1:27 PM]  Kumar, Subodh:  
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 444, in wrap_socket
    cnx.do_handshake()
  File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1443, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1191, in _raise_ssl_error
    _raise_current_error()
  File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')] 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connection.py", line 356, in connect
    ssl_context=context)
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 450, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='server_name.com', port=443): Max retries exceeded with url: //api/2.3/auth/signin (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Anaconda3\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 114, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\tableauserverclient\server\endpoint\auth_endpoint.py", line 30, in sign_in
    **self.parent_srv.http_options)
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py", line 511, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='server_name.com', port=443): Max retries exceeded with url: //api/2.3/auth/signin (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))

**Comment by sks786** [comment]
@RussTheAerialist , I hope you will help me.

**Comment by acknapp** [comment]
@sks786 your issue is slightly different than @HarveySummers.  The issue that you are dealing with is because the Tableau server that you are trying to connect to is using a self signed certificate (this is assuming that your server is not actually being named server_name.com).  If you look at sample/set_http_options.py on line 36 there is an option to not verify SSL.  You'll want to add this line into your code as well.  That should at least get past the current SSL error you're dealing with.

**Comment by irwando** [comment]
@HarveySummers If you are still in need please try again with the latest version of TSC.  Please open a new issue if it is still a problem.
