### ISSUE TITLE
Server.datasources.download() returns XML parsing error

### ISSUE THREAD

**Issue by sbliefnick1** [tableau/server-client-python#397]
I had this code written as follows (simplified), and it was working in production for many days. Then today it failed with the below error. The only thing that I can think of that might be related to our particular Tableau Server instance is that last night our admin scaled up the available space, but I don't see why that would affect this. 

Our Server version is 2018.3.2 (20183.18.1214.0808) 64-bit Windows, and the code is being executed from a CentOS 7.5 box using Python 3.5. I also tried running it with Python 3.5 from my Mac High Sierra 10.13.6. TSC version 0.7

```
import tableauserverclient as TSC

server = TSC.Server('https://myorg.org', use_server_version=True)
tableau_authentiction = TSC.TableauAuth('my_valid_user', 'my_valid_password)
server.auth.sign_in(tableau_authentication)

ds_id = '000000a-000a-000a-000a-00000000000a'  # valid data source id

server.datasources.download(ds_id, filepath='/my/valid/filepath.tdsx', include_extract=False)
```

I know the authentication and data source IDs are right because I've tried multiple valid IDs and get the same error every time: 

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/anaconda3/envs/fauteuil/lib/python3.5/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 114, in wrapper
    return func(self, *args, **kwargs)
  File "/anaconda3/envs/fauteuil/lib/python3.5/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 152, in wrapper
    return func(self, *args, **kwargs)
  File "/anaconda3/envs/fauteuil/lib/python3.5/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 152, in wrapper
    return func(self, *args, **kwargs)
  File "/anaconda3/envs/fauteuil/lib/python3.5/site-packages/tableauserverclient/server/endpoint/datasources_endpoint.py", line 100, in download
    with closing(self.get_request(url, parameters={'stream': True})) as server_response:
  File "/anaconda3/envs/fauteuil/lib/python3.5/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 73, in get_request
    request_object=request_object, parameters=parameters)
  File "/anaconda3/envs/fauteuil/lib/python3.5/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 54, in _make_request
    self._check_status(server_response)
  File "/anaconda3/envs/fauteuil/lib/python3.5/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 66, in _check_status
    raise ServerResponseError.from_response(server_response.content, self.parent_srv.namespace)
  File "/anaconda3/envs/fauteuil/lib/python3.5/site-packages/tableauserverclient/server/endpoint/exceptions.py", line 17, in from_response
    parsed_response = ET.fromstring(resp)
  File "/anaconda3/envs/fauteuil/lib/python3.5/xml/etree/ElementTree.py", line 1344, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: mismatched tag: line 31, column 77
```

**Comment by shinchris** [comment]
Seems likely that the server responded with an error. Could you try running your script with logging enabled? It'll give us more information about what http request was sent to the server.
You can enable logging by adding these lines to your script:
```
import logging
logging.basicConfig(level="DEBUG")
```

**Comment by sbliefnick1** [comment]
My Server admin fixed it, and if I understand her correctly, she said that in the process of upgrading the storage space, she copied over the application server to a new server instead of rebuilding the whole thing from scratch. This had the effect that Tableau thought it was being run in a distributed environment, and some of it was pointing to the old server which was offline, so my script couldn't access the data store. I just wanted to record that here in case anyone else had the same problem. We can close this issue. Thanks.
