### ISSUE TITLE
Request options for Datasources produce wrong xml

### ISSUE THREAD

**Issue by 1oglop1** [tableau/server-client-python#413]
Hi, am I doing something wrong or request XML is incorrectly created?

```
source_server.version = '3.2'

req_option = tsc.RequestOptions()
req_option.filter.add(
    tsc.Filter(
        tsc.RequestOptions.Field.Name,
        tsc.RequestOptions.Operator.In,
        [con.datasource_name for con in workbook.connections]
    )
)
datasources, pagination_item = source_server.datasources.get(req_option)
```

produce this error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/user/.virtualenvs/tableau-venv/lib/python3.6/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 114, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/user/.virtualenvs/tableau-venv/lib/python3.6/site-packages/tableauserverclient/server/endpoint/datasources_endpoint.py", line 37, in get
    server_response = self.get_request(url, req_options)
  File "/Users/user/.virtualenvs/tableau-venv/lib/python3.6/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 73, in get_request
    request_object=request_object, parameters=parameters)
  File "/Users/user/.virtualenvs/tableau-venv/lib/python3.6/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 54, in _make_request
    self._check_status(server_response)
  File "/Users/user/.virtualenvs/tableau-venv/lib/python3.6/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 66, in _check_status
    raise ServerResponseError.from_response(server_response.content, self.parent_srv.namespace)
  File "/Users/user/.virtualenvs/tableau-venv/lib/python3.6/site-packages/tableauserverclient/server/endpoint/exceptions.py", line 17, in from_response
    parsed_response = ET.fromstring(resp)
  File "/Users/user/.pyenv/versions/3.6.6/lib/python3.6/xml/etree/ElementTree.py", line 1315, in XML
    return parser.close()
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

@t8y8 - is this repository still maintained, issues are piling up there are quite few old PRs

**Comment by irwando** [comment]
Sorry for the delay, I'm trying to catch up!  Can you please try the latest version of TSC and let me know if this is still an issue? Thanks!

**Comment by bcantoni** [comment]
I'm going to close due to age. If this is still an issue please reopen with details requested.
