### ISSUE TITLE
Issue with changing workbook's owner

### ISSUE THREAD

**Issue by AmeyMankar** [tableau/server-client-python#426]
I am trying to change the workbook's owner using following code:  
`request_options = TSC.RequestOptions(pagesize=1000)
        all_workbooks = list(TSC.Pager(server.workbooks, request_options))

        for workbook in all_workbooks:
            if workbook.name == 'report-test' and workbook.project_name=='folder-Test':
                workbook.owner = 'new_owner'
                print('Trying to update the owner')
                workbook = server.workbooks.update(workbook)
                print('Owner changed successfully')`

I am getting following error:  

> Traceback (most recent call last):
  File "tsc_refresh_schedule.py", line 124, in <module>
    main()
  File "tsc_refresh_schedule.py", line 65, in main
    run(args)
  File "tsc_refresh_schedule.py", line 100, in run
    workbook = server.workbooks.update(workbook)
  File "/usr/local/lib/python3.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 116, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tableauserverclient/server/endpoint/workbooks_endpoint.py", line 84, in update
    server_response = self.put_request(url, update_req)
  File "/usr/local/lib/python3.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 85, in put_request
    content_type=content_type)
  File "/usr/local/lib/python3.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 54, in _make_request
    self._check_status(server_response)
  File "/usr/local/lib/python3.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 68, in _check_status
    raise ServerResponseError.from_response(server_response.content, self.parent_srv.namespace)
tableauserverclient.server.endpoint.exceptions.ServerResponseError: 

	400000: Bad Request
		Payload is either malformed XML/JSON or incomplete

Can someone please help me out?  
TIA

**Comment by shinchris** [comment]
For updating the owner of a workbook, you will need to change the `owner_id` field of the workbook to a valid user ID.
