### ISSUE TITLE
datasource.refresh fails

### ISSUE THREAD

**Issue by propername** [tableau/server-client-python#543]
I assume the `tableauserverclient` is merely a wrapper for the rest API.

Our tableau server is using the rest api version 3.5 which may contribute to why this is failing.

```
import tableauserverclient as TSC
server = TSC.Server(server_address=base_url())
conn = server.auth.sign_in(auth_req=tableau_auth)
conn
# <tableauserverclient.server.server.Server object at 0x000002F2620C9B00>

TSC.Pager(conn.datasources)
# <tableauserverclient.server.pager.Pager object at 0x000002F262109F28>

def by_name(items: list) -> dict:
    return {item.name: item for item in items}
dss = convert.by_name(TSC.Pager(conn.datasources))
dss
#{'Claim Dashboard (emp)': <tableauserverclient.models.datasource_item.DatasourceItem object at 0x000002F262109EF0>, 'Net Rate Outliers Source (emp)': <tableauserverclient.models.datasource_item.DatasourceItem object at 0x000002F262109F60>, 'Custom SQL Query (BIG_prod) Source (emp)': <tableauserverclient.models.datasource_item.DatasourceItem object at 0x000002F26211E0B8>, 'Claim Dashboard (sec)': <tableauserverclient.models.datasource_item.DatasourceItem object at 0x000002F26211E160>, 'Payroll Outliers Source (emp)': <tableauserverclient.models.datasource_item.DatasourceItem object at 0x000002F26211E278>, 'Topline Scorecard Source 2020 (emp) ': <tableauserverclient.models.datasource_item.DatasourceItem object at 0x000002F26211E0F0>, 'NB Topline Scorecard Source (emp)': <tableauserverclient.models.datasource_item.DatasourceItem object at 0x000002F26211E198>, 'NB Topline Scorecard Source 2020 (emp)': <tableauserverclient.models.datasource_item.DatasourceItem object at 0x000002F26211E1D0>, 'Topline Scorecard Source (emp)': <tableauserverclient.models.datasource_item.DatasourceItem object at 0x000002F26211E208>}

dss['NB Topline Scorecard Source (emp)']
#<tableauserverclient.models.datasource_item.DatasourceItem object at 0x000002F26211E198>

dss['NB Topline Scorecard Source (emp)'].id
#'bb2feb6d-3c83-4fc3-93be-0ed0439fd608'

conn.datasources.refresh(dss['NB Topline Scorecard Source (emp)'])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\tableauserverclient\server\endpoint\datasources_endpoint.py", line 152, in refresh
    server_response = self.post_request(url, empty_req)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 96, in post_request
    content_type=content_type)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 55, in _make_request
    self._check_status(server_response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 70, in _check_status
    raise ServerResponseError.from_response(server_response.content, self.parent_srv.namespace)
tableauserverclient.server.endpoint.exceptions.ServerResponseError:

        404008: Resource Not Found
                API version '2.3' does not support access to the given resource.
```

So does the TSC use an old version of the rest API unless specified or something?

**Comment by propername** [comment]
`conn.use_server_version()`

found it.
