### ISSUE TITLE
Error server.auth.sign_in(tableau_auth) - xml.etree.ElementTree.ParseError: mismatched tag

### ISSUE THREAD

**Issue by shrikantla** [tableau/server-client-python#552]
Hello All!

I'm having some trouble with signing in.
Here is the sample standard code snippet I am using - replacing with dummy credentials/url .
I am using tableauserverclient==0.8.1, due to some internal dependency conflict on urllib3 library
Tableau Server Version is 2019.4.0

import tableauserverclient as TSC

tableau_auth = TSC.TableauAuth("user_abc", "password_abc", "Default")
server = TSC.Server("https://tableau-abc.xyz.com/")

with server.auth.sign_in(tableau_auth):   ( <-- failing here)
...

and I am getting the following error

Traceback (most recent call last):
  File "tableau_refresh_extract.py", line 68, in <module>
    main()
  File "tableau_refresh_extract.py", line 36, in main
    with server.auth.sign_in(tableau_auth):
  File "/srv/venvs/service/trusty/service_venv/local/lib/python2.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 116, in wrapper
    return func(self, *args, **kwargs)
  File "/srv/venvs/service/trusty/service_venv/local/lib/python2.7/site-packages/tableauserverclient/server/endpoint/auth_endpoint.py", line 33, in sign_in
    parsed_response = ET.fromstring(server_response.content)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 1256, column 4

**Comment by willjdsouza** [comment]
i am having the same issue, not sure what is going on

**Comment by shrikantla** [comment]
I was able to fix it, it was endpoint authentication issue with our internal setup
