### ISSUE TITLE
Python2 error:

### ISSUE THREAD

**Issue by chy9002** [tableau/server-client-python#766]
Cannot run with python2 after 14.0, logs:

```
Traceback (most recent call last):
  File "/mnt/mesos/sandbox/resources/0000002283417/resource.refreshman2.py", line 5, in <module>
    import tableauserverclient as TSC
  File "/usr/lib/python2.7/site-packages/tableauserverclient/__init__.py", line 8, in <module>
    from .server import RequestOptions, CSVRequestOptions, ImageRequestOptions, PDFRequestOptions, Filter, Sort, \
  File "/usr/lib/python2.7/site-packages/tableauserverclient/server/__init__.py", line 9, in <module>
    from .endpoint import Auth, DataAlerts, Datasources, Endpoint, Groups, Projects, Schedules, \
  File "/usr/lib/python2.7/site-packages/tableauserverclient/server/endpoint/__init__.py", line 4, in <module>
    from .datasources_endpoint import Datasources
  File "/usr/lib/python2.7/site-packages/tableauserverclient/server/endpoint/datasources_endpoint.py", line 5, in <module>
    from .resource_tagger import _ResourceTagger
  File "/usr/lib/python2.7/site-packages/tableauserverclient/server/endpoint/resource_tagger.py", line 7, in <module>
    import urllib.parse
ImportError: No module named parse
```

**Comment by bcantoni** [comment]
@chy9002 that's correct - the library only supports running under Python version 3.5 or newer. You _may_ be able to use an older version of the TSC library, but the recommended solution would be to move to Python 3.x.

**Comment by chy9002** [comment]
> @chy9002 that's correct - the library only supports running under Python version 3.5 or newer. You _may_ be able to use an older version of the TSC library, but the recommended solution would be to move to Python 3.x.

Thanks for your reply.
