### ISSUE TITLE
AttributeError: 'WorkbookItem' object has no attribute 'get'

### ISSUE THREAD

**Issue by kathraji** [tableau/server-client-python#810]
I'm using the below code to find out id of the workbook using its name and then download the workbook from the server.But I'm getting below error when executing the same. I'm doing anything wrong here?

```
all_workbooks, pagination_item = server.workbooks.get()
  for workbook in all_workbooks:
   if workbook.get('name') == workbook_name:
     return workbook.get('id')
  error = "Workbook named '{0}' not found.".format(workbook_name)
  raise LookupError(error)

#with server.auth.sign_in(tableau_auth):
workbook_id = get_workbook_id(workbook_name)
filepath = server.workbooks.download(workbook_id,None,no_extract=False)
```

Error:

```
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    workbook_id = get_workbook_id(workbook_name)
  File "test.py", line 29, in get_workbook_id
    if workbook.get('name') == workbook_name:
AttributeError: 'WorkbookItem' object has no attribute 'get'
```

**Comment by bcantoni** [comment]
@kathraji from your sample code there it looks like you intend `get_workbook_id()` (the first section of code) to return the workbook ID as a string. To do that, you can change your code to access the attribute as `workbook.id`.

In other words try the following:

```
all_workbooks, pagination_item = server.workbooks.get()
for workbook in all_workbooks:
    if workbook.get('name') == workbook_name:
        return workbook.id
    error = "Workbook named '{0}' not found.".format(workbook_name)
    raise LookupError(error)
```
