### ISSUE TITLE
'Jobs' object has no attribute 'wait_for_job'

### ISSUE THREAD

**Issue by yo-lvgs** [tableau/server-client-python#962]
**Describe the bug**
Hi,
I got the error 【'Jobs' object has no attribute 'wait_for_job'】 when I ran my code,would you tell me how to solve it?

**Versions**
Details of your environment, including:
 - Tableau Server version (or note if using Tableau Online)
   - Tableau Online 
 - Python version
   - Python 3.7 
 - TSC library version
   - 3.13(I also tried 3.1 and 3.5 but got the same error) 

**To Reproduce**
Steps to reproduce the behavior. Please include a code snippet where possible.

```
    tableau_auth = TSC.TableauAuth(user_name, password, site_id=site_id)
    server = TSC.Server(site_url)

    server.version = '3.13'
    server.auth.sign_in(tableau_auth)

    get_info_for_project_id = [proj for proj in TSC.Pager(server.projects) if proj.name == 'lt_bigquery_test']
    project_id = get_info_for_project_id[0].id

    with server.auth.sign_in(tableau_auth):
        for datasource in TSC.Pager(server.datasources.get):
            if datasource.project_name == 'lt_bigquery_test':
                datasource = server.datasources.get_by_id(datasource.id)
                refreshed_datasource = server.datasources.refresh(datasource)
                print("Waiting for job...")
                job = server.jobs.wait_for_job(refreshed_datasource)
                print("Job finished succesfully")
```
**Results**
What are the results or error messages received?

```
Waiting for job...
Traceback (most recent call last):
  File "/Users/reika.yo/dev/lt-datainfra-etl/workflows/ltsf2BQ/refresh_tableau_datasource_new.py", line 49, in <module>
    refresh_tableau_datasource()
  File "/Users/reika.yo/dev/lt-datainfra-etl/workflows/ltsf2BQ/refresh_tableau_datasource_new.py", line 45, in refresh_tableau_datasource
    job = server.jobs.wait_for_job(refreshed_datasource)
```

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by jorwoods** [comment]
TSC version is not the same as Tableau Server version. The latest TSC version is 0.17. `wait_for_job` is only available in 0.17 and later. Fix the issue by running `pip install --upgrade tableauserverclient`.

**Comment by jorwoods** [comment]
You also want to consider using `server = TSC.Server(site_url, True)` so that TSC automatically fetches and sets the API version, rather than you manually setting it.
